# Generated by Django 2.1.5 on 2019-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='choice_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='poll',
            new_name='question',
        ),
    ]
