# Generated by Django 2.1.5 on 2019-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190204_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
