# Generated by Django 2.1.5 on 2019-02-22 13:10

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190220_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=api.models.Blog, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
